name: LinkedIn AutoPoster

on:
  schedule:
    - cron: '0 8,12,17,21 * * *' 
  workflow_dispatch:          

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install fonts
        run: sudo apt-get install -y fonts-liberation
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create token.txt
        run: echo "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" > token.txt
      
      - name: Run autoposter
        run: python main.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}